### ISSUE TITLE
Actividad 1, Mapa Mental, Edgar Fabian Castro Pérez

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-1-mapa-mental-11042002#1]
[Actividad 1, MapaMental, Edgar Fabian Castro Pérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-11042002/files/9466734/Actividad.1.MapaMental.Edgar.Fabian.Castro.Perez.pdf)

**Comment by Jaczibeth** [comment]
de 20% de la actividad obtuviste el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
